package com.example.crateproxy;

import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Savepoint;
import java.sql.Statement;
import java.sql.Struct;
import java.lang.reflect.InvocationHandler;
import java.lang.reflect.Proxy;
import java.sql.ResultSet;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

/**
 * CrateDB JDBC proxy connection wrapper.
 * Swallows commit/rollback/setAutoCommit since CrateDB does not support transactions.
 * Wraps createStatement and prepareStatement factories to return proxy wrappers.
 * All other methods delegate to the real pgJDBC connection.
 */
public class CrateProxyConnection implements Connection {

    private final Connection real;

    CrateProxyConnection(Connection real) {
        this.real = real;
    }

    // -------------------------------------------------------------------------
    // Stub Savepoint — prevents NPE when Liquibase calls rollback(Savepoint)
    // -------------------------------------------------------------------------
    private static final Savepoint STUB_SAVEPOINT = new Savepoint() {
        @Override public int getSavepointId() { return 0; }
        @Override public String getSavepointName() { return "stub"; }
    };

    // -------------------------------------------------------------------------
    // INTERCEPTED: Transaction management — all no-ops (PRXY-03)
    // -------------------------------------------------------------------------

    @Override
    public void commit() throws SQLException {
        // no-op: CrateDB auto-commits; swallow silently
    }

    @Override
    public void rollback() throws SQLException {
        // no-op: no transaction to roll back
    }

    @Override
    public void rollback(Savepoint savepoint) throws SQLException {
        // no-op: savepoints are stubs
    }

    @Override
    public void setAutoCommit(boolean autoCommit) throws SQLException {
        // no-op: always auto-commit
    }

    @Override
    public boolean getAutoCommit() throws SQLException {
        return true;
    }

    @Override
    public Savepoint setSavepoint() throws SQLException {
        return STUB_SAVEPOINT;
    }

    @Override
    public Savepoint setSavepoint(String name) throws SQLException {
        return STUB_SAVEPOINT;
    }

    @Override
    public void releaseSavepoint(Savepoint savepoint) throws SQLException {
        // no-op
    }

    // -------------------------------------------------------------------------
    // INTERCEPTED: Statement factories — wrap in proxy classes
    // -------------------------------------------------------------------------

    @Override
    public Statement createStatement() throws SQLException {
        return new CrateProxyStatement(real.createStatement());
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
        return new CrateProxyStatement(real.createStatement(resultSetType, resultSetConcurrency));
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return new CrateProxyStatement(real.createStatement(resultSetType, resultSetConcurrency, resultSetHoldability));
    }

    @Override
    public PreparedStatement prepareStatement(String sql) throws SQLException {
        String rewritten = SqlRewriter.rewrite(sql);
        if (rewritten == null) {
            return new CrateProxyPreparedStatement(null, true);
        }
        return new CrateProxyPreparedStatement(real.prepareStatement(rewritten), false);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        String rewritten = SqlRewriter.rewrite(sql);
        if (rewritten == null) {
            return new CrateProxyPreparedStatement(null, true);
        }
        return new CrateProxyPreparedStatement(real.prepareStatement(rewritten, autoGeneratedKeys), false);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        String rewritten = SqlRewriter.rewrite(sql);
        if (rewritten == null) {
            return new CrateProxyPreparedStatement(null, true);
        }
        return new CrateProxyPreparedStatement(real.prepareStatement(rewritten, resultSetType, resultSetConcurrency), false);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        String rewritten = SqlRewriter.rewrite(sql);
        if (rewritten == null) {
            return new CrateProxyPreparedStatement(null, true);
        }
        return new CrateProxyPreparedStatement(real.prepareStatement(rewritten, resultSetType, resultSetConcurrency, resultSetHoldability), false);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
        String rewritten = SqlRewriter.rewrite(sql);
        if (rewritten == null) {
            return new CrateProxyPreparedStatement(null, true);
        }
        return new CrateProxyPreparedStatement(real.prepareStatement(rewritten, columnIndexes), false);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
        String rewritten = SqlRewriter.rewrite(sql);
        if (rewritten == null) {
            return new CrateProxyPreparedStatement(null, true);
        }
        return new CrateProxyPreparedStatement(real.prepareStatement(rewritten, columnNames), false);
    }

    @Override
    public CallableStatement prepareCall(String sql) throws SQLException {
        return real.prepareCall(sql);
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        return real.prepareCall(sql, resultSetType, resultSetConcurrency);
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return real.prepareCall(sql, resultSetType, resultSetConcurrency, resultSetHoldability);
    }

    // -------------------------------------------------------------------------
    // DELEGATED: All other Connection methods
    // -------------------------------------------------------------------------

    @Override
    public String nativeSQL(String sql) throws SQLException {
        return real.nativeSQL(sql);
    }

    @Override
    public boolean isClosed() throws SQLException {
        return real.isClosed();
    }

    @Override
    public DatabaseMetaData getMetaData() throws SQLException {
        DatabaseMetaData realMeta = real.getMetaData();
        // Wrap DatabaseMetaData to intercept getIndexInfo: pgJDBC's implementation calls
        // pg_catalog.pg_get_indexdef which CrateDB doesn't support. Returning an empty
        // ResultSet causes Liquibase to evaluate indexExists preconditions as false,
        // triggering onFail="MARK_RAN" instead of halting with onError=HALT.
        InvocationHandler handler = (proxy, method, args) -> {
            String mName = method.getName();
            // Intercept catalog-introspection methods that pgJDBC implements via pg_catalog
            // queries CrateDB does not support. Return an empty ResultSet so Liquibase
            // evaluates all existence-preconditions as "object does not exist", triggering
            // onFail="MARK_RAN" to skip changesets gracefully.
            // getIndexInfo: pgJDBC calls pg_catalog.pg_get_indexdef — unsupported by CrateDB
            // getColumns: pgJDBC calls pg_catalog.pg_attribute — may return 0-column ResultSet
            if ("getIndexInfo".equals(mName) || "getColumns".equals(mName)) {
                try {
                    ResultSet rs = (ResultSet) method.invoke(realMeta, args);
                    // If ResultSet has 0 columns the JDBC spec was violated — replace with empty
                    if (rs != null && rs.getMetaData().getColumnCount() == 0) {
                        rs.close();
                        System.err.println("[CRATE PROXY] " + mName + " returned 0-column ResultSet, replacing with empty");
                        return real.createStatement().executeQuery("SELECT 1 WHERE 1=0");
                    }
                    return rs;
                } catch (Exception e) {
                    System.err.println("[CRATE PROXY] " + mName + " failed (" + e.getMessage() + "), returning empty ResultSet");
                    return real.createStatement().executeQuery("SELECT 1 WHERE 1=0");
                }
            }
            try {
                return method.invoke(realMeta, args);
            } catch (java.lang.reflect.InvocationTargetException e) {
                throw e.getCause() != null ? e.getCause() : e;
            }
        };
        return (DatabaseMetaData) Proxy.newProxyInstance(
            DatabaseMetaData.class.getClassLoader(),
            new Class<?>[]{ DatabaseMetaData.class },
            handler
        );
    }

    @Override
    public void setReadOnly(boolean readOnly) throws SQLException {
        real.setReadOnly(readOnly);
    }

    @Override
    public boolean isReadOnly() throws SQLException {
        return real.isReadOnly();
    }

    @Override
    public void setCatalog(String catalog) throws SQLException {
        real.setCatalog(catalog);
    }

    @Override
    public String getCatalog() throws SQLException {
        return real.getCatalog();
    }

    @Override
    public void setTransactionIsolation(int level) throws SQLException {
        // Silently swallow — CrateDB doesn't support isolation level changes
        // but callers (Hibernate/Keycloak) set this and expect no error
    }

    @Override
    public int getTransactionIsolation() throws SQLException {
        return Connection.TRANSACTION_READ_COMMITTED;
    }

    @Override
    public SQLWarning getWarnings() throws SQLException {
        return real.getWarnings();
    }

    @Override
    public void clearWarnings() throws SQLException {
        real.clearWarnings();
    }

    @Override
    public Map<String, Class<?>> getTypeMap() throws SQLException {
        return real.getTypeMap();
    }

    @Override
    public void setTypeMap(Map<String, Class<?>> map) throws SQLException {
        real.setTypeMap(map);
    }

    @Override
    public void setHoldability(int holdability) throws SQLException {
        real.setHoldability(holdability);
    }

    @Override
    public int getHoldability() throws SQLException {
        return real.getHoldability();
    }

    @Override
    public Clob createClob() throws SQLException {
        return real.createClob();
    }

    @Override
    public Blob createBlob() throws SQLException {
        return real.createBlob();
    }

    @Override
    public NClob createNClob() throws SQLException {
        return real.createNClob();
    }

    @Override
    public SQLXML createSQLXML() throws SQLException {
        return real.createSQLXML();
    }

    @Override
    public boolean isValid(int timeout) throws SQLException {
        return real.isValid(timeout);
    }

    @Override
    public void setClientInfo(String name, String value) throws SQLClientInfoException {
        real.setClientInfo(name, value);
    }

    @Override
    public void setClientInfo(Properties properties) throws SQLClientInfoException {
        real.setClientInfo(properties);
    }

    @Override
    public String getClientInfo(String name) throws SQLException {
        return real.getClientInfo(name);
    }

    @Override
    public Properties getClientInfo() throws SQLException {
        return real.getClientInfo();
    }

    @Override
    public Array createArrayOf(String typeName, Object[] elements) throws SQLException {
        return real.createArrayOf(typeName, elements);
    }

    @Override
    public Struct createStruct(String typeName, Object[] attributes) throws SQLException {
        return real.createStruct(typeName, attributes);
    }

    @Override
    public void setSchema(String schema) throws SQLException {
        real.setSchema(schema);
    }

    @Override
    public String getSchema() throws SQLException {
        return real.getSchema();
    }

    @Override
    public void abort(Executor executor) throws SQLException {
        real.abort(executor);
    }

    @Override
    public void setNetworkTimeout(Executor executor, int milliseconds) throws SQLException {
        real.setNetworkTimeout(executor, milliseconds);
    }

    @Override
    public int getNetworkTimeout() throws SQLException {
        return real.getNetworkTimeout();
    }

    @Override
    public void close() throws SQLException {
        real.close();
    }

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException {
        return real.unwrap(iface);
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) throws SQLException {
        return real.isWrapperFor(iface);
    }
}
