package com.example.crateproxy;

import java.io.InputStream;
import java.io.Reader;
import java.math.BigDecimal;
import java.net.URL;
import java.sql.Array;
import java.sql.Blob;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.Date;
import java.sql.NClob;
import java.sql.ParameterMetaData;
import java.sql.PreparedStatement;
import java.sql.Ref;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.RowId;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.Calendar;

/**
 * CrateDB JDBC proxy prepared statement wrapper.
 * SQL is rewritten at prepare time (in CrateProxyConnection.prepareStatement).
 * When swallowed=true, all execute methods return no-op values and all setXxx calls are silently ignored.
 */
public class CrateProxyPreparedStatement implements PreparedStatement {

    private final PreparedStatement real; // null when swallowed
    private final boolean swallowed;

    CrateProxyPreparedStatement(PreparedStatement real, boolean swallowed) {
        this.real = real;
        this.swallowed = swallowed;
    }

    // -------------------------------------------------------------------------
    // INTERCEPTED: PreparedStatement execute methods
    // -------------------------------------------------------------------------

    @Override
    public boolean execute() throws SQLException {
        if (swallowed) return false;
        return real.execute();
    }

    @Override
    public ResultSet executeQuery() throws SQLException {
        if (swallowed) {
            throw new SQLException("CRATE PROXY: executeQuery() called on swallowed PreparedStatement");
        }
        return real.executeQuery();
    }

    @Override
    public int executeUpdate() throws SQLException {
        if (swallowed) return 0;
        return real.executeUpdate();
    }

    // -------------------------------------------------------------------------
    // INTERCEPTED: Statement execute* with SQL arg — also route through rewriter
    // -------------------------------------------------------------------------

    @Override
    public boolean execute(String sql) throws SQLException {
        String rewritten = SqlRewriter.rewrite(sql);
        if (rewritten == null) return false;
        if (swallowed) return false;
        return real.execute(rewritten);
    }

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        String rewritten = SqlRewriter.rewrite(sql);
        if (rewritten == null || swallowed) {
            return real != null ? real.executeQuery("SELECT 1 WHERE 1=0") : null;
        }
        return real.executeQuery(rewritten);
    }

    @Override
    public int executeUpdate(String sql) throws SQLException {
        String rewritten = SqlRewriter.rewrite(sql);
        if (rewritten == null) return 0;
        if (swallowed) return 0;
        return real.executeUpdate(rewritten);
    }

    @Override
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        String rewritten = SqlRewriter.rewrite(sql);
        if (rewritten == null || swallowed) return false;
        return real.execute(rewritten, autoGeneratedKeys);
    }

    @Override
    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        String rewritten = SqlRewriter.rewrite(sql);
        if (rewritten == null || swallowed) return false;
        return real.execute(rewritten, columnIndexes);
    }

    @Override
    public boolean execute(String sql, String[] columnNames) throws SQLException {
        String rewritten = SqlRewriter.rewrite(sql);
        if (rewritten == null || swallowed) return false;
        return real.execute(rewritten, columnNames);
    }

    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        String rewritten = SqlRewriter.rewrite(sql);
        if (rewritten == null || swallowed) return 0;
        return real.executeUpdate(rewritten, autoGeneratedKeys);
    }

    @Override
    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        String rewritten = SqlRewriter.rewrite(sql);
        if (rewritten == null || swallowed) return 0;
        return real.executeUpdate(rewritten, columnIndexes);
    }

    @Override
    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        String rewritten = SqlRewriter.rewrite(sql);
        if (rewritten == null || swallowed) return 0;
        return real.executeUpdate(rewritten, columnNames);
    }

    @Override
    public void addBatch(String sql) throws SQLException {
        String rewritten = SqlRewriter.rewrite(sql);
        if (rewritten != null && !swallowed) real.addBatch(rewritten);
    }

    @Override
    public void addBatch() throws SQLException {
        if (!swallowed) real.addBatch();
    }

    // -------------------------------------------------------------------------
    // setXxx parameter methods — no-op when swallowed, delegate otherwise
    // -------------------------------------------------------------------------

    @Override
    public void setNull(int parameterIndex, int sqlType) throws SQLException {
        if (!swallowed) real.setNull(parameterIndex, sqlType);
    }

    @Override
    public void setBoolean(int parameterIndex, boolean x) throws SQLException {
        if (!swallowed) real.setBoolean(parameterIndex, x);
    }

    @Override
    public void setByte(int parameterIndex, byte x) throws SQLException {
        if (!swallowed) real.setByte(parameterIndex, x);
    }

    @Override
    public void setShort(int parameterIndex, short x) throws SQLException {
        if (!swallowed) real.setShort(parameterIndex, x);
    }

    @Override
    public void setInt(int parameterIndex, int x) throws SQLException {
        if (!swallowed) real.setInt(parameterIndex, x);
    }

    @Override
    public void setLong(int parameterIndex, long x) throws SQLException {
        if (!swallowed) real.setLong(parameterIndex, x);
    }

    @Override
    public void setFloat(int parameterIndex, float x) throws SQLException {
        if (!swallowed) real.setFloat(parameterIndex, x);
    }

    @Override
    public void setDouble(int parameterIndex, double x) throws SQLException {
        if (!swallowed) real.setDouble(parameterIndex, x);
    }

    @Override
    public void setBigDecimal(int parameterIndex, BigDecimal x) throws SQLException {
        if (!swallowed) real.setBigDecimal(parameterIndex, x);
    }

    @Override
    public void setString(int parameterIndex, String x) throws SQLException {
        if (!swallowed) real.setString(parameterIndex, x);
    }

    @Override
    public void setBytes(int parameterIndex, byte[] x) throws SQLException {
        if (!swallowed) real.setBytes(parameterIndex, x);
    }

    @Override
    public void setDate(int parameterIndex, Date x) throws SQLException {
        if (!swallowed) real.setDate(parameterIndex, x);
    }

    @Override
    public void setTime(int parameterIndex, Time x) throws SQLException {
        if (!swallowed) real.setTime(parameterIndex, x);
    }

    @Override
    public void setTimestamp(int parameterIndex, Timestamp x) throws SQLException {
        if (!swallowed) real.setTimestamp(parameterIndex, x);
    }

    @Override
    public void setAsciiStream(int parameterIndex, InputStream x, int length) throws SQLException {
        if (!swallowed) real.setAsciiStream(parameterIndex, x, length);
    }

    @Override
    @SuppressWarnings("deprecation")
    public void setUnicodeStream(int parameterIndex, InputStream x, int length) throws SQLException {
        if (!swallowed) real.setUnicodeStream(parameterIndex, x, length);
    }

    @Override
    public void setBinaryStream(int parameterIndex, InputStream x, int length) throws SQLException {
        if (!swallowed) real.setBinaryStream(parameterIndex, x, length);
    }

    @Override
    public void clearParameters() throws SQLException {
        if (!swallowed) real.clearParameters();
    }

    @Override
    public void setObject(int parameterIndex, Object x, int targetSqlType) throws SQLException {
        if (!swallowed) real.setObject(parameterIndex, x, targetSqlType);
    }

    @Override
    public void setObject(int parameterIndex, Object x) throws SQLException {
        if (!swallowed) real.setObject(parameterIndex, x);
    }

    @Override
    public void setCharacterStream(int parameterIndex, Reader reader, int length) throws SQLException {
        if (!swallowed) real.setCharacterStream(parameterIndex, reader, length);
    }

    @Override
    public void setRef(int parameterIndex, Ref x) throws SQLException {
        if (!swallowed) real.setRef(parameterIndex, x);
    }

    @Override
    public void setBlob(int parameterIndex, Blob x) throws SQLException {
        if (!swallowed) real.setBlob(parameterIndex, x);
    }

    @Override
    public void setClob(int parameterIndex, Clob x) throws SQLException {
        if (!swallowed) real.setClob(parameterIndex, x);
    }

    @Override
    public void setArray(int parameterIndex, Array x) throws SQLException {
        if (!swallowed) real.setArray(parameterIndex, x);
    }

    @Override
    public ResultSetMetaData getMetaData() throws SQLException {
        if (swallowed) return null;
        return real.getMetaData();
    }

    @Override
    public void setDate(int parameterIndex, Date x, Calendar cal) throws SQLException {
        if (!swallowed) real.setDate(parameterIndex, x, cal);
    }

    @Override
    public void setTime(int parameterIndex, Time x, Calendar cal) throws SQLException {
        if (!swallowed) real.setTime(parameterIndex, x, cal);
    }

    @Override
    public void setTimestamp(int parameterIndex, Timestamp x, Calendar cal) throws SQLException {
        if (!swallowed) real.setTimestamp(parameterIndex, x, cal);
    }

    @Override
    public void setNull(int parameterIndex, int sqlType, String typeName) throws SQLException {
        if (!swallowed) real.setNull(parameterIndex, sqlType, typeName);
    }

    @Override
    public void setURL(int parameterIndex, URL x) throws SQLException {
        if (!swallowed) real.setURL(parameterIndex, x);
    }

    @Override
    public ParameterMetaData getParameterMetaData() throws SQLException {
        if (swallowed) return null;
        return real.getParameterMetaData();
    }

    @Override
    public void setRowId(int parameterIndex, RowId x) throws SQLException {
        if (!swallowed) real.setRowId(parameterIndex, x);
    }

    @Override
    public void setNString(int parameterIndex, String value) throws SQLException {
        if (!swallowed) real.setNString(parameterIndex, value);
    }

    @Override
    public void setNCharacterStream(int parameterIndex, Reader value, long length) throws SQLException {
        if (!swallowed) real.setNCharacterStream(parameterIndex, value, length);
    }

    @Override
    public void setNClob(int parameterIndex, NClob value) throws SQLException {
        if (!swallowed) real.setNClob(parameterIndex, value);
    }

    @Override
    public void setClob(int parameterIndex, Reader reader, long length) throws SQLException {
        if (!swallowed) real.setClob(parameterIndex, reader, length);
    }

    @Override
    public void setBlob(int parameterIndex, InputStream inputStream, long length) throws SQLException {
        if (!swallowed) real.setBlob(parameterIndex, inputStream, length);
    }

    @Override
    public void setNClob(int parameterIndex, Reader reader, long length) throws SQLException {
        if (!swallowed) real.setNClob(parameterIndex, reader, length);
    }

    @Override
    public void setSQLXML(int parameterIndex, SQLXML xmlObject) throws SQLException {
        if (!swallowed) real.setSQLXML(parameterIndex, xmlObject);
    }

    @Override
    public void setObject(int parameterIndex, Object x, int targetSqlType, int scaleOrLength) throws SQLException {
        if (!swallowed) real.setObject(parameterIndex, x, targetSqlType, scaleOrLength);
    }

    @Override
    public void setAsciiStream(int parameterIndex, InputStream x, long length) throws SQLException {
        if (!swallowed) real.setAsciiStream(parameterIndex, x, length);
    }

    @Override
    public void setBinaryStream(int parameterIndex, InputStream x, long length) throws SQLException {
        if (!swallowed) real.setBinaryStream(parameterIndex, x, length);
    }

    @Override
    public void setCharacterStream(int parameterIndex, Reader reader, long length) throws SQLException {
        if (!swallowed) real.setCharacterStream(parameterIndex, reader, length);
    }

    @Override
    public void setAsciiStream(int parameterIndex, InputStream x) throws SQLException {
        if (!swallowed) real.setAsciiStream(parameterIndex, x);
    }

    @Override
    public void setBinaryStream(int parameterIndex, InputStream x) throws SQLException {
        if (!swallowed) real.setBinaryStream(parameterIndex, x);
    }

    @Override
    public void setCharacterStream(int parameterIndex, Reader reader) throws SQLException {
        if (!swallowed) real.setCharacterStream(parameterIndex, reader);
    }

    @Override
    public void setNCharacterStream(int parameterIndex, Reader value) throws SQLException {
        if (!swallowed) real.setNCharacterStream(parameterIndex, value);
    }

    @Override
    public void setClob(int parameterIndex, Reader reader) throws SQLException {
        if (!swallowed) real.setClob(parameterIndex, reader);
    }

    @Override
    public void setBlob(int parameterIndex, InputStream inputStream) throws SQLException {
        if (!swallowed) real.setBlob(parameterIndex, inputStream);
    }

    @Override
    public void setNClob(int parameterIndex, Reader reader) throws SQLException {
        if (!swallowed) real.setNClob(parameterIndex, reader);
    }

    // -------------------------------------------------------------------------
    // DELEGATED: Remaining Statement methods
    // -------------------------------------------------------------------------

    @Override
    public void close() throws SQLException {
        if (!swallowed) real.close();
    }

    @Override
    public int getMaxFieldSize() throws SQLException {
        if (swallowed) return 0;
        return real.getMaxFieldSize();
    }

    @Override
    public void setMaxFieldSize(int max) throws SQLException {
        if (!swallowed) real.setMaxFieldSize(max);
    }

    @Override
    public int getMaxRows() throws SQLException {
        if (swallowed) return 0;
        return real.getMaxRows();
    }

    @Override
    public void setMaxRows(int max) throws SQLException {
        if (!swallowed) real.setMaxRows(max);
    }

    @Override
    public void setEscapeProcessing(boolean enable) throws SQLException {
        if (!swallowed) real.setEscapeProcessing(enable);
    }

    @Override
    public int getQueryTimeout() throws SQLException {
        if (swallowed) return 0;
        return real.getQueryTimeout();
    }

    @Override
    public void setQueryTimeout(int seconds) throws SQLException {
        if (!swallowed) real.setQueryTimeout(seconds);
    }

    @Override
    public void cancel() throws SQLException {
        if (!swallowed) real.cancel();
    }

    @Override
    public SQLWarning getWarnings() throws SQLException {
        if (swallowed) return null;
        return real.getWarnings();
    }

    @Override
    public void clearWarnings() throws SQLException {
        if (!swallowed) real.clearWarnings();
    }

    @Override
    public void setCursorName(String name) throws SQLException {
        if (!swallowed) real.setCursorName(name);
    }

    @Override
    public ResultSet getResultSet() throws SQLException {
        if (swallowed) return null;
        return real.getResultSet();
    }

    @Override
    public int getUpdateCount() throws SQLException {
        if (swallowed) return -1;
        return real.getUpdateCount();
    }

    @Override
    public boolean getMoreResults() throws SQLException {
        if (swallowed) return false;
        return real.getMoreResults();
    }

    @Override
    public void setFetchDirection(int direction) throws SQLException {
        if (!swallowed) real.setFetchDirection(direction);
    }

    @Override
    public int getFetchDirection() throws SQLException {
        if (swallowed) return ResultSet.FETCH_FORWARD;
        return real.getFetchDirection();
    }

    @Override
    public void setFetchSize(int rows) throws SQLException {
        if (!swallowed) real.setFetchSize(rows);
    }

    @Override
    public int getFetchSize() throws SQLException {
        if (swallowed) return 0;
        return real.getFetchSize();
    }

    @Override
    public int getResultSetConcurrency() throws SQLException {
        if (swallowed) return ResultSet.CONCUR_READ_ONLY;
        return real.getResultSetConcurrency();
    }

    @Override
    public int getResultSetType() throws SQLException {
        if (swallowed) return ResultSet.TYPE_FORWARD_ONLY;
        return real.getResultSetType();
    }

    @Override
    public void clearBatch() throws SQLException {
        if (!swallowed) real.clearBatch();
    }

    @Override
    public int[] executeBatch() throws SQLException {
        if (swallowed) return new int[0];
        return real.executeBatch();
    }

    @Override
    public Connection getConnection() throws SQLException {
        if (swallowed) return null;
        return real.getConnection();
    }

    @Override
    public boolean getMoreResults(int current) throws SQLException {
        if (swallowed) return false;
        return real.getMoreResults(current);
    }

    @Override
    public ResultSet getGeneratedKeys() throws SQLException {
        if (swallowed) return null;
        return real.getGeneratedKeys();
    }

    @Override
    public int getResultSetHoldability() throws SQLException {
        if (swallowed) return ResultSet.CLOSE_CURSORS_AT_COMMIT;
        return real.getResultSetHoldability();
    }

    @Override
    public boolean isClosed() throws SQLException {
        if (swallowed) return false;
        return real.isClosed();
    }

    @Override
    public void setPoolable(boolean poolable) throws SQLException {
        if (!swallowed) real.setPoolable(poolable);
    }

    @Override
    public boolean isPoolable() throws SQLException {
        if (swallowed) return false;
        return real.isPoolable();
    }

    @Override
    public void closeOnCompletion() throws SQLException {
        if (!swallowed) real.closeOnCompletion();
    }

    @Override
    public boolean isCloseOnCompletion() throws SQLException {
        if (swallowed) return false;
        return real.isCloseOnCompletion();
    }

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException {
        if (swallowed) throw new SQLException("CRATE PROXY: unwrap on swallowed PreparedStatement");
        return real.unwrap(iface);
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) throws SQLException {
        if (swallowed) return false;
        return real.isWrapperFor(iface);
    }
}
