package com.example.crateproxy;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Statement;

/**
 * CrateDB JDBC proxy statement wrapper.
 * Routes all execute* methods through SqlRewriter before forwarding to the real statement.
 * Returns safe no-op values when SqlRewriter returns null (swallowed statement).
 */
public class CrateProxyStatement implements Statement {

    private final Statement real;

    CrateProxyStatement(Statement real) {
        this.real = real;
    }

    // -------------------------------------------------------------------------
    // INTERCEPTED: All execute* paths — route through SqlRewriter
    // -------------------------------------------------------------------------

    @Override
    public boolean execute(String sql) throws SQLException {
        String rewritten = SqlRewriter.rewrite(sql);
        if (rewritten == null) return false;
        return real.execute(rewritten);
    }

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        String rewritten = SqlRewriter.rewrite(sql);
        if (rewritten == null) {
            return real.executeQuery("SELECT 1 WHERE 1=0");
        }
        return real.executeQuery(rewritten);
    }

    @Override
    public int executeUpdate(String sql) throws SQLException {
        String rewritten = SqlRewriter.rewrite(sql);
        if (rewritten == null) return 0;
        return real.executeUpdate(rewritten);
    }

    @Override
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        String rewritten = SqlRewriter.rewrite(sql);
        if (rewritten == null) return false;
        return real.execute(rewritten, autoGeneratedKeys);
    }

    @Override
    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        String rewritten = SqlRewriter.rewrite(sql);
        if (rewritten == null) return false;
        return real.execute(rewritten, columnIndexes);
    }

    @Override
    public boolean execute(String sql, String[] columnNames) throws SQLException {
        String rewritten = SqlRewriter.rewrite(sql);
        if (rewritten == null) return false;
        return real.execute(rewritten, columnNames);
    }

    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        String rewritten = SqlRewriter.rewrite(sql);
        if (rewritten == null) return 0;
        return real.executeUpdate(rewritten, autoGeneratedKeys);
    }

    @Override
    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        String rewritten = SqlRewriter.rewrite(sql);
        if (rewritten == null) return 0;
        return real.executeUpdate(rewritten, columnIndexes);
    }

    @Override
    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        String rewritten = SqlRewriter.rewrite(sql);
        if (rewritten == null) return 0;
        return real.executeUpdate(rewritten, columnNames);
    }

    @Override
    public void addBatch(String sql) throws SQLException {
        String rewritten = SqlRewriter.rewrite(sql);
        if (rewritten != null) real.addBatch(rewritten);
    }

    // -------------------------------------------------------------------------
    // DELEGATED: All other Statement methods
    // -------------------------------------------------------------------------

    @Override
    public void close() throws SQLException {
        real.close();
    }

    @Override
    public int getMaxFieldSize() throws SQLException {
        return real.getMaxFieldSize();
    }

    @Override
    public void setMaxFieldSize(int max) throws SQLException {
        real.setMaxFieldSize(max);
    }

    @Override
    public int getMaxRows() throws SQLException {
        return real.getMaxRows();
    }

    @Override
    public void setMaxRows(int max) throws SQLException {
        real.setMaxRows(max);
    }

    @Override
    public void setEscapeProcessing(boolean enable) throws SQLException {
        real.setEscapeProcessing(enable);
    }

    @Override
    public int getQueryTimeout() throws SQLException {
        return real.getQueryTimeout();
    }

    @Override
    public void setQueryTimeout(int seconds) throws SQLException {
        real.setQueryTimeout(seconds);
    }

    @Override
    public void cancel() throws SQLException {
        real.cancel();
    }

    @Override
    public SQLWarning getWarnings() throws SQLException {
        return real.getWarnings();
    }

    @Override
    public void clearWarnings() throws SQLException {
        real.clearWarnings();
    }

    @Override
    public void setCursorName(String name) throws SQLException {
        real.setCursorName(name);
    }

    @Override
    public ResultSet getResultSet() throws SQLException {
        return real.getResultSet();
    }

    @Override
    public int getUpdateCount() throws SQLException {
        return real.getUpdateCount();
    }

    @Override
    public boolean getMoreResults() throws SQLException {
        return real.getMoreResults();
    }

    @Override
    public void setFetchDirection(int direction) throws SQLException {
        real.setFetchDirection(direction);
    }

    @Override
    public int getFetchDirection() throws SQLException {
        return real.getFetchDirection();
    }

    @Override
    public void setFetchSize(int rows) throws SQLException {
        real.setFetchSize(rows);
    }

    @Override
    public int getFetchSize() throws SQLException {
        return real.getFetchSize();
    }

    @Override
    public int getResultSetConcurrency() throws SQLException {
        return real.getResultSetConcurrency();
    }

    @Override
    public int getResultSetType() throws SQLException {
        return real.getResultSetType();
    }

    @Override
    public void clearBatch() throws SQLException {
        real.clearBatch();
    }

    @Override
    public int[] executeBatch() throws SQLException {
        return real.executeBatch();
    }

    @Override
    public Connection getConnection() throws SQLException {
        return real.getConnection();
    }

    @Override
    public boolean getMoreResults(int current) throws SQLException {
        return real.getMoreResults(current);
    }

    @Override
    public ResultSet getGeneratedKeys() throws SQLException {
        return real.getGeneratedKeys();
    }

    @Override
    public int getResultSetHoldability() throws SQLException {
        return real.getResultSetHoldability();
    }

    @Override
    public boolean isClosed() throws SQLException {
        return real.isClosed();
    }

    @Override
    public void setPoolable(boolean poolable) throws SQLException {
        real.setPoolable(poolable);
    }

    @Override
    public boolean isPoolable() throws SQLException {
        return real.isPoolable();
    }

    @Override
    public void closeOnCompletion() throws SQLException {
        real.closeOnCompletion();
    }

    @Override
    public boolean isCloseOnCompletion() throws SQLException {
        return real.isCloseOnCompletion();
    }

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException {
        return real.unwrap(iface);
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) throws SQLException {
        return real.isWrapperFor(iface);
    }
}
